# Generated by Django 3.2.9 on 2021-12-23 10:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='favourite',
            old_name='owner',
            new_name='favourtie_owner',
        ),
    ]
