# Generated by Django 3.2.9 on 2021-12-23 10:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_rename_owner_favourite_favourtie_owner'),
    ]

    operations = [
        migrations.RenameField(
            model_name='favourite',
            old_name='favourtie_owner',
            new_name='favourite_owner',
        ),
    ]
