# Generated by Django 3.2.9 on 2021-12-23 07:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_alter_registration_advertisements'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='registration',
            name='advertisements',
        ),
    ]
