# Generated by Django 3.2.9 on 2022-01-08 13:36

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_alter_images_advertisement'),
    ]

    operations = [
        migrations.AddField(
            model_name='advertisement',
            name='status',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='advertisement',
            name='rent_fee',
            field=models.PositiveIntegerField(default=10, validators=[django.core.validators.MinValueValidator(10000), django.core.validators.MaxValueValidator(100000)]),
        ),
    ]
