# Generated by Django 3.2.9 on 2022-01-10 12:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_auto_20211223_1538'),
        ('home', '0004_remove_registration_advertisements'),
        ('home', '0009_alter_advertisement_owner'),
    ]

    operations = [
    ]
